[node_reqs]
ComfyUI-VideoHelperSuite = "Kosinkadink/ComfyUI-VideoHelperSuite"
ComfyUI-KJNodes = "kijai/ComfyUI-KJNodes"
ComfyUI-GeometryPack= "PozzettiAndrea/ComfyUI-GeometryPack"

[target.osx-arm64.dependencies]
av = "*"
ffmpeg = "*"
