[node_packs]
ComfyUI-VideoHelperSuite = "Kosinkadink/ComfyUI-VideoHelperSuite"
ComfyUI-KJNodes = "kijai/ComfyUI-KJNodes"
ComfyUI-GeometryPack= "PozzettiAndrea/ComfyUI-GeometryPack"
ComfyUI-CameraPack= "PozzettiAndrea/ComfyUI-CameraPack"