[test]
levels = ["syntax", "javascript", "coverage", "install", "registration", "instantiation", "execution"]

[test.workflows]
cpu = ["advanced_3d_multiview", "advanced", "advanced_3d", "simple"]
cuda = "all"

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "linux_cuda", "windows_cuda", "windows_desktop", "windows_portable_cuda","macos_desktop","windows_desktop_cuda"]  